{"event": "verbose", "uuid": "deac67f5-c7d7-4e7e-bad0-0e838ef45b7a", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/root/python/Network/ansible/playbooks/roles/ip_config/tasks/main.yml': line 2, column 3, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "4d43b685-e476-492e-bbdc-2fb8e8577e91", "created": "2025-01-20T15:15:50.829835+00:00"}