{"event": "verbose", "uuid": "51e168a9-8908-4e6e-a377-c49e1e787721", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/root/Network_App/ansible/playbooks/roles/ospf/tasks/main.yml': line 15, column 5, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "6fb7e08a-6255-4fa5-87d9-f51e3957ed4c", "created": "2025-02-13T06:45:21.318999+00:00"}