{"event": "verbose", "uuid": "73df68f8-b819-46e2-b216-7cd6c2a150c7", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/root/python/Network/ansible/playbooks/roles/ip_config/tasks/main.yml': line 2, column 3, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "27630bdb-753b-4e72-a050-199dc9a9f22c", "created": "2025-01-20T15:15:48.341749+00:00"}